version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: products
      MONGO_INITDB_ROOT_USERNAME: frogadmin
      MONGO_INITDB_ROOT_PASSWORD: Froggy419
    volumes:
      - mongodb-data:/data/db

  #authentication is done against admin database

  product-service:
    image: products-service:latest
    container_name: products-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

#docker build -t products-service . command to create image

volumes:
  mongodb-data:
